
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 24 20:04:11 CDT 2022
//----------------------------------------------------

package fes.aragon.compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ABAJO = 5;
  public static final int LLLAVE = 8;
  public static final int ARRIBA = 4;
  public static final int VFRUTA = 11;
  public static final int EOF = 0;
  public static final int IZQUIERDA = 6;
  public static final int NUMERO = 14;
  public static final int ESPACIO = 12;
  public static final int error = 1;
  public static final int DERECHA = 7;
  public static final int COLOCA = 2;
  public static final int PUNTOYCOMA = 13;
  public static final int MOVER = 3;
  public static final int REPETIR = 10;
  public static final int RLLAVE = 9;
}

